language: python
python:
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
# command to install dependencies
before_install:
  - curl -L http://bootstrap.saltstack.org | sudo sh -s
  - sudo cp salt/minion /etc/salt/minion
  - sudo service salt-minion restart
  
  # debugging
  - sudo cat /var/log/salt/*
  - sudo salt-call grains.items --local
  
  - cd tildes
install:
  - pip install -r requirements.txt -r requirements-dev.txt
  - npm install
  - sudo cat /var/log/salt/*
  - sudo salt-call state.show_highstate --local --retcode-passthrough -l info
  - sudo salt-call state.apply --local --retcode-passthrough -l info
# command to run tests
before_script: cd tildes
script:
  - pytest
  - mypy .
  - black --check .
  - prospector
  - npm run lint
