language: python
python:
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
# command to install dependencies
before_install:
  - sudo apt-get -y install cmark
  - cd tildes
install:
  - pip install -r requirements.txt -r requirements-dev.txt
  - npm install
# command to run tests
before_script: cd tildes
script:
  - pytest
  - mypy .
  - black --check .
  - prospector
  - npm run lint
