dist: bionic
language: python

install:
  # Install libvrt & KVM
  - sudo apt-get update
  - sudo apt-get install -y bridge-utils dnsmasq-base ebtables libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev

  # Download Vagrant & Install Vagrant package
  - sudo wget -nv https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_x86_64.deb
  - sudo dpkg -i vagrant_2.2.9_x86_64.deb

  # Vagrant correctly installed?
  - vagrant --version

  # Install vagrant-libvirt Vagrant plugin
  - sudo vagrant plugin install vagrant-libvirt

script:
  - sudo vagrant up --provider=libvirt
  
  - sudo vagrant ssh -c ". activate && pytest"
  - sudo vagrant ssh -c ". activate && mypy ."
  - sudo vagrant ssh -c ". activate && black --check ."
  - sudo vagrant ssh -c ". activate && prospector"
  - sudo vagrant ssh -c ". activate && npm run lint"
